//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEngSoft.Properties
{
  using System;


  /// <summary>
  ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
  /// </summary>
  // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
  // através de uma ferramenta como ResGen ou Visual Studio.
  // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
  // com a opção /str, ou recrie o projeto do VS.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources()
    {
    }

    /// <summary>
    ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppEngSoft.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
    ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap alarm
    {
      get
      {
        object obj = ResourceManager.GetObject("alarm", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap bar_chart
    {
      get
      {
        object obj = ResourceManager.GetObject("bar-chart", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap breda_profile
    {
      get
      {
        object obj = ResourceManager.GetObject("breda_profile", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap enzo_profile
    {
      get
      {
        object obj = ResourceManager.GetObject("enzo_profile", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap gui_profile
    {
      get
      {
        object obj = ResourceManager.GetObject("gui_profile", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_add_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_add_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_add_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_add_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_add_481
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_add_481", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_close_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_close_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_close_321
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_close_321", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_close_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_close_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_collaborator_male_256
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_collaborator_male_256", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_customer_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_customer_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_edit_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_edit_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_maximize_button_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_maximize_button_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_minimize_window_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_minimize_window_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_person_male_skin_type_4_128
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_person_male_skin_type_4_128", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_product_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_product_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_restore_down_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_restore_down_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_shopping_cart_128
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_shopping_cart_128", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_shopping_cart_32
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_shopping_cart_32", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_shopping_cart_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_shopping_cart_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_supplier_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_supplier_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap icons8_trash_48
    {
      get
      {
        object obj = ResourceManager.GetObject("icons8_trash_48", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap male_user_96px
    {
      get
      {
        object obj = ResourceManager.GetObject("male_user_96px", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap male_user_96px1
    {
      get
      {
        object obj = ResourceManager.GetObject("male_user_96px1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap male_user_96px2
    {
      get
      {
        object obj = ResourceManager.GetObject("male_user_96px2", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap maracci_profile
    {
      get
      {
        object obj = ResourceManager.GetObject("maracci_profile", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap settings
    {
      get
      {
        object obj = ResourceManager.GetObject("settings", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap shopping_cart
    {
      get
      {
        object obj = ResourceManager.GetObject("shopping-cart", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap shopping_list
    {
      get
      {
        object obj = ResourceManager.GetObject("shopping-list", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap value
    {
      get
      {
        object obj = ResourceManager.GetObject("value", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap value_1
    {
      get
      {
        object obj = ResourceManager.GetObject("value_1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap victor_profile
    {
      get
      {
        object obj = ResourceManager.GetObject("victor_profile", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
  }
}
